producto1= input("Ingrese nombre del primer producto comprado")
valor1= float(input("Ingrese el valor del producto"))
cantidad1= int(input("Ingrese la cantidad del producto"))
total1= (valor1*cantidad1)
print (total1)
producto2= input("Ingrese nombre del segundo producto comprado")
valor2= float(input("Ingrese el valor del producto"))
cantidad2= int(input("Ingrese cantidad del producto"))
total2= (valor2*cantidad2)
print (total2)
producto3=input("Ingrese nombre del tercer producto comprado")
valor3=float(input("Ingrese valor del producto"))
cantidad3=int(input("Ingrese cantidad del producto"))
total3= (valor3*cantidad3)
print (total3)
producto4=input("Ingrese nombre del cuarto producto comprado")
valor4= float(input("Ingrese valor del producto"))
cantidad4=int(input("Ingrese cantidad del producto"))
total4= (valor4*cantidad4)
print (total4)
total5= (total1+total2+total3+total4)
print ("Total " + str(total5))
print ("Ha comprado " + str(cantidad1) +  str(producto1) + " a un precio unitario de " + str(valor1) + " por un total de " + str(total1))
print ("Ha comprado " + str(cantidad2) +  str(producto2) + " a un precio unitario de " + str(valor2) + " por un total de " + str(total2))
print ("Ha comprado " + str(cantidad3) +  str(producto3) + " a un precio unitario de " + str(valor3) + " por un total de " + str(total3))
print ("Ha comprado " + str(cantidad4) +  str(producto4) + " a un precio unitario de " + str(valor4) + " por un total de " + str(total4))
print ("Ha gastado en total " + str(total5)) 